### ISSUE TITLE
Remove @utils directive

### ISSUE THREAD

**Issue by erikcs** [som-shahlab/survmetabench#36]
This line: https://github.com/som-shahlab/survmetabench/blob/master/survlearners/R/scoxph.R#L1 can be removed from all files @CrystalXuR, if you want to try and do a simple branch for that

**Comment by CrystalXuR** [comment]
Sounds good. Trying it now

**Comment by erikcs** [comment]
Remeber to do a search in the entire repo for "@utils" and remove it from all files

**Comment by CrystalXuR** [comment]
I removed all the ones under the R folder, but do I also need to remove the one at
[https://github.com/som-shahlab/survmetabench/blob/master/simulation_hpc.R#L25](url)

**Comment by erikcs** [comment]
Are you going to send new PRs for these issues? you closed and deleted all the open ones?

**Comment by CrystalXuR** [comment]
I am going to start over and send new PRs for each issue. I intended to merge my changes under #44 to master after you approved it, but it did not happen. I still do not know why, and I think I lost all the changes I made since last night :(

**Comment by erikcs** [comment]
Ok, it sounds like you learned a lesson the hard way = less likely to make the same mistake twice! your changes are most likely still on your local git

**Comment by CrystalXuR** [comment]
really, Is there an easy way to check it
