### ISSUE TITLE
Remove stringr dependency

### ISSUE THREAD

**Issue by erikcs** [som-shahlab/survmetabench#37]
This line https://github.com/som-shahlab/survmetabench/blob/master/survlearners/R/utils.R#L64 can be replaced by `paste0("covariate_", 1:ncol(x))`

and `stringr` can be deleted in this line https://github.com/som-shahlab/survmetabench/blob/master/survlearners/DESCRIPTION#L28

if you want to practice som PR branch workflow @CrystalXuR

**Comment by CrystalXuR** [comment]
I made the replacement as you suggested... and I assume the stringr will be deleted automatically in the future recompiling

**Comment by erikcs** [comment]
You made the replacement, where? In a new PR?

**Comment by erikcs** [comment]
Oh I see you made it in the utils branch, if you want to practice git workflow you can do it in two separate branches. that's also good practice to separate PRs into disjoint changes (in the future it will make the git history easier to read)

**Comment by CrystalXuR** [comment]
That is a very suggestion. I will keep that in mind in the future
