### ISSUE TITLE
Remove unnecessary function from utils.R

### ISSUE THREAD

**Issue by erikcs** [som-shahlab/survmetabench#48]
All these last helper functions can be removed:
https://github.com/som-shahlab/survmetabench/blob/master/survlearners/R/utils.R#L215 
as they serve no purpose.

Also you shouldn't call into function from testthat (expect_equal) inside the package

**Comment by CrystalXuR** [comment]
Oh, those are the code from the R-learner repo. I took the utils.R file from Xinkun. I will go through them and fix things later

**Comment by erikcs** [comment]
Ok, remember to consider adding xinkun as "contributor" here https://github.com/som-shahlab/survmetabench/blob/master/survlearners/DESCRIPTION#L4 if this repo started out building on the rlearner repo

**Comment by CrystalXuR** [comment]
I will discuss it further with @nignatiadis
