### ISSUE TITLE
Address some R CMD check doc fixes

### ISSUE THREAD

**Issue by erikcs** [som-shahlab/survmetabench#5]
@CrystalXuR if you open the .Rproj file in the survlearners/ folder you can run R's package check ("R CMD check") through R studio

If you run it now you will get 1 warning:

```
> checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'Fgrf'
    ‘weight’ ‘alpha’ ‘meta_learner’
  Documented arguments not in \usage in documentation object 'Fgrf':
    ‘mtry’ ‘min.node.size’ ‘postprocess’
 ```
etc if you want to try and address these in a PR? (i.e. add the new documentation entries in the .R files, generate the documentation by running Build -> Document, commit the files both .R and .Rd, then run Build -> Check Package to emulate the automated package test that is run on GitHub actions on a PR)

Getting warnings/errors in R CMD check = failure, getting "NOTE" is OK but should ideally be avoided

**Comment by CrystalXuR** [comment]
Resolved
