### ISSUE TITLE
Add required libraries to imports

### ISSUE THREAD

**Issue by erikcs** [som-shahlab/survmetabench#6]
also, no need to rely on the stringr package only to do this https://github.com/som-shahlab/Metalearners-Benchmark/blob/master/survlearners/R/utils.R#L13

**Comment by CrystalXuR** [comment]
Note to Crystal: always do glmnet::glmnet etc when calling external packages

**Comment by erikcs** [comment]
No this is not over yet since we can remove the stringr package req. by doing https://github.com/som-shahlab/Metalearners-Benchmark/blob/master/survlearners/R/utils.R#L13 in base R

**Comment by erikcs** [comment]
You also use the `survival` package but it is not in imports

Need to keep this in mind if you use Surv and formulas when doing :: 

https://cran.r-project.org/web/packages/survival/survival.pdf page 35
>One user mistake that has recently arisen is to slavishly follow the advice of some coding guides and
prepend survival:: onto everthing, including the special terms, e.g., survival::coxph(survival:Surv(time,status)
~ age + survival::cluster(inst),data=lung) First, this is unnecessary: arguments within the
coxph call will be evaluated within the survival namespace, so another package’s Surv or cluster
function would not be noticed. (Full qualification of the coxph call itself may be protective, however.) Second, and more importantly, the call just above will not give the correct answer. The specials are recognized by their name, and survival::cluster is not the same as cluster; the above
model would treat inst as an ordinary variable. A similar issue arises from using stats::offset
as a term, in either survival or glm models.
