### ISSUE TITLE
Avoid brackets [ in docstring

### ISSUE THREAD

**Issue by erikcs** [som-shahlab/survmetabench#62]
Writing [E\[X | U\]](https://github.com/som-shahlab/survmetabench/blob/master/r-package/survlearners/R/rlasgrf.R#L11) in docstrings confuses R:

![Screen Shot 2022-04-08 at 17 38 48](https://user-images.githubusercontent.com/7185264/162549647-9cc5fa4d-f143-4d10-8423-e8a4667630b8.png)

let's use parenthesis `E(X | Y)` everywhere. Please update files affected @CrystalXuR

**Comment by CrystalXuR** [comment]
sounds good
