### ISSUE TITLE
Some :: still missing for grf

### ISSUE THREAD

**Issue by erikcs** [som-shahlab/survmetabench#65]
For examples in do.call in some files like:

https://github.com/som-shahlab/survmetabench/blob/master/r-package/survlearners/R/rlasgrf.R#L136

it's only for survival_forest

**Comment by CrystalXuR** [comment]
For this particular example, should I do _do.call(survival_forest...)_

**Comment by erikcs** [comment]
`do.call(grf::survival_forest...`

**Comment by CrystalXuR** [comment]
yeah, that is what I mean, sorry, typed too fast
